// w_70, h_53
export const cardsData = [
  {
    id: 1,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644301407/Build_yyhbji.png",
    line: "card_p3",
  },
  {
    id: 2,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644300376/03_uncglu.jpg",
    line: "card_p2",
  },
  {
    id: 3,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644300377/04_sv1tze.jpg",
    line: "card_p1",
  },
  {
    id: 4,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644301284/Mask_Group_2_bij84b.png",
    line: "card_p6",
  },
  {
    id: 5,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644300364/06_rc5qjz.png",
    line: "card_p5",
  },
  {
    id: 6,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644300379/11_xlxmkb.jpg",
    line: "card_p4",
  },
  {
    id: 7,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644302114/Mask_Group_3_ugev9n.png",
    line: "card_p9",
  },
  {
    id: 8,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644301983/Mask_Group_4_yghutn.png",
    line: "card_p8",
  },
  {
    id: 9,
    photo:
      "https://res.cloudinary.com/dm1mlee94/image/upload/w_275,h_230,c_scale/v1644300358/10_bxehok.png",
    line: "card_p7",
  },
];

export const categories = {
  Contractor: [
    {
      value: "Electrical",
    },
    {
      value: "HVAC",
    },
    {
      value: "Plumbing",
    },
    {
      value: "Civil Works",
    },
    {
      value: "Finish Works",
    },
    {
      value: "Fire Fighting",
    },
    {
      value: "Complete Project",
    }
  ],
  Handyman: [
    {
      value: "Electrical",
    },
    {
      value: "Plumbing",
    },
    {
      value: "HVAC",
    }
  ],
  DesignerConsultantFirm: [
    {
      value: "Building Designers",
    }
  ],
};

export const subCategories = {
  Contractor: {
    "Electrical": [
      { value: "Electrical (Medium Voltage) Contractors" },
      { value: "Low Current (Telephone, date, TV)  Contractors" },
      { value: "Camera and CCTV  Contractors" },
      { value: "Fire Alarm  Contractors" },
      { value: "Electrical (High Voltage)  Contractors" },
      { value: "Complete Electrical Contractors  Contractors" }
    ],
    "HVAC": [
      { value: "Split AC Installation" },
      { value: "Concealled and Package AC installation" },
      { value: "VRV and VRF Installation" },
      { value: "Chiller Instalation" },
      { value: "Complete HVAC contracting company" }
    ],
    "Plumbing": [
      { value: "Plumbing contractors inside building works" },
      { value: "Main sever line works" },
      { value: "Swimming Pool, Jacouzi and Suana works" },
      { value: "Garden Sprinkler works" },
      { value: "Irrigation piping works" },
    ],
    "Civil Works": [
      { value: "Steel Work" },
      { value: "Shutttering wood Work" },
      { value: "Scafolding works" },
      { value: "Concrete works" },
      { value: "Plaster Works" },
      { value: "Block Works" },
      { value: "Plaster Works" },
      { value: "All Civil Works Contractors" },
    ],
    "Finish Works": [
      { value: "Steel doors and Decoration" },
      { value: "Wood works Doors etc" },
      { value: "Windows Aluminium" },
      { value: "Glass works" },
      { value: "Paint Work" },
      { value: "Gyps and Gypsumboards" },
      { value: "Ceiling works" },
      { value: "Wallpaper works" },
    ],
    "Fire Fighting": [
      { value: "Firefighting Piping" },
      { value: "Firealarm works" },
      { value: "Complete Firefighting Contractors" },
    ],
    "Complete Project": [
      { value: "Complete Project Handover Companies" },
    ],
  },
  Handyman: {
    "Electrical": [
      "Electrical (Medium Voltage) handymen",
      "Low Current (Telephone, date, TV)  handymen",
      "Camera and CCTV  handymen",
      "Fire Alarm  handymen",
      "Electrical (High Voltage)  handymen",
      "Complete Electrical maintenance company"
    ],
    "Plumbing": [
      "Plumbing Technician",
      "Swimming Pool, Jacouzi and Suana works",
      "Garden Sprinkler and Irrigation Technician"
    ],
    "HVAC": [
      "Split and Cassete technician",
      "Concealled and Package technician",
      "VRV and VRF technician",
      "Chiller system technician",
      "Complete HVAC Maintenance Company"
    ]
  },
  DesignerConsultantFirm: {
    "Building Designers":
      [
        { value: "Civil Structure Designers" },
        { value: "Archetect/Finishing  Designers" },
        { value: "Mechanical System Designers" },
        { value: "Electrical System Designers" },
        { value: "Plumbing Designers" },
        { value: "HVAC Designers" },
        { value: "Firefighting System Designers" },
        { value: "All System Design Companies" },
      ]
  },
};

export const users = [
  {
    label: "Handyman",
    value: "Handyman",
  },
  {
    label: "Contractor",
    value: "Contractor",
  },
  {
    label: "DesignerConsultantFirm",
    value: "DesignerConsultantFirm",
  },
];

export const countries = [
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Pakistan", label: "Pakistan" },
];


export const pakCities = [
  "Ahmed Nager Chatha",
  "Ahmadpur East",
  "Ali Khan Abad",
  "Alipur",
  "Arifwala",
  "Attock",
  "Bhera",
  "Bhalwal",
  "Bahawalnagar",
  "Bahawalpur",
  "Bhakkar",
  "Burewala",
  "Chillianwala",
  "Chakwal",
  "Chichawatni",
  "Chiniot",
  "Chishtian",
  "Daska",
  "Darya Khan",
  "Dera Ghazi Khan",
  "Dhaular",
  "Dina",
  "Dinga",
  "Dipalpur",
  "Faisalabad",
  "Ferozewala",
  "Fateh Jhang",
  "Ghakhar Mandi",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Gujar Khan",
  "Hafizabad",
  "Haroonabad",
  "Hasilpur",
  "Haveli Lakha",
  "Jatoi",
  "Jalalpur",
  "Jattan",
  "Jampur",
  "Jaranwala",
  "Jhang",
  "Jhelum",
  "Kalabagh",
  "Karor Lal Esan",
  "Kasur",
  "Kamalia",
  "Kamoke",
  "Khanewal",
  "Khanpur",
  "Kharian",
  "Khushab",
  "Kot Addu",
  "Jauharabad",
  "Lahore",
  "Lalamusa",
  "Layyah",
  "Liaquat Pur",
  "Lodhran",
  "Malakwal",
  "Mamoori",
  "Mailsi",
  "Mandi Bahauddin",
  "Mian Channu",
  "Mianwali",
  "Multan",
  "Murree",
  "Muridke",
  "Mianwali Bangla",
  "Muzaffargarh",
  "Narowal",
  "Nankana Sahib",
  "Okara",
  "Renala Khurd",
  "Pakpattan",
  "Pattoki",
  "Pir Mahal",
  "Qaimpur",
  "Qila Didar Singh",
  "Rabwah",
  "Raiwind",
  "Rajanpur",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sadiqabad",
  "Safdarabad",
  "Sahiwal",
  "Sangla Hill",
  "Sarai Alamgir",
  "Sargodha",
  "Shakargarh",
  "Sheikhupura",
  "Sialkot",
  "Sohawa",
  "Soianwala",
  "Siranwali",
  "Talagang",
  "Taxila",
  "Toba Tek Singh",
  "Vehari",
  "Wah Cantonment",
  "Wazirabad",
  "Badin",
  "Bhirkan",
  "Rajo Khanani",
  "Chak",
  "Dadu",
  "Digri",
  "Diplo",
  "Dokri",
  "Ghotki",
  "Haala",
  "Hyderabad",
  "Islamkot",
  "Jacobabad",
  "Jamshoro",
  "Jungshahi",
  "Kandhkot",
  "Kandiaro",
  "Karachi",
  "Kashmore",
  "Keti Bandar",
  "Khairpur",
  "Kotri",
  "Larkana",
  "Matiari",
  "Mehar",
  "Mirpur Khas",
  "Mithani",
  "Mithi",
  "Mehrabpur",
  "Moro",
  "Nagarparkar",
  "Naudero",
  "Naushahro Feroze",
  "Naushara",
  "Nawabshah",
  "Nazimabad",
  "Qambar",
  "Qasimabad",
  "Ranipur",
  "Ratodero",
  "Rohri",
  "Sakrand",
  "Sanghar",
  "Shahbandar",
  "Shahdadkot",
  "Shahdadpur",
  "Shahpur Chakar",
  "Shikarpaur",
  "Sukkur",
  "Tangwani",
  "Tando Adam Khan",
  "Tando Allahyar",
  "Tando Muhammad Khan",
  "Thatta",
  "Umerkot",
  "Warah",
  "Abbottabad",
  "Adezai",
  "Alpuri",
  "Akora Khattak",
  "Ayubia",
  "Banda Daud Shah",
  "Bannu",
  "Batkhela",
  "Battagram",
  "Birote",
  "Chakdara",
  "Charsadda",
  "Chitral",
  "Daggar",
  "Dargai",
  "Dera Ismail Khan",
  "Doaba",
  "Dir",
  "Drosh",
  "Hangu",
  "Haripur",
  "Karak",
  "Kohat",
  "Kulachi",
  "Lakki Marwat",
  "Latamber",
  "Madyan",
  "Mansehra",
  "Mardan",
  "Mastuj",
  "Mingora",
  "Nowshera",
  "Paharpur",
  "Pabbi",
  "Peshawar",
  "Saidu Sharif",
  "Shorkot",
  "Shewa Adda",
  "Swabi",
  "Swat",
  "Tangi",
  "Tank",
  "Thall",
  "Timergara",
  "Tordher",
  "Awaran",
  "Barkhan",
  "Chagai",
  "Dera Bugti",
  "Gwadar",
  "Harnai",
  "Jafarabad",
  "Jhal Magsi",
  "Kacchi",
  "Kalat",
  "Kech",
  "Kharan",
  "Khuzdar",
  "Killa Abdullah",
  "Killa Saifullah",
  "Kohlu",
  "Lasbela",
  "Lehri",
  "Loralai",
  "Mastung",
  "Musakhel",
  "Nasirabad",
  "Nushki",
  "Panjgur",
  "Pishin Valley",
  "Quetta",
  "Sherani",
  "Sibi",
  "Sohbatpur",
  "Washuk",
  "Zhob",
  "Ziarat",
];


export const saudiCities = [
  "Abhā", "Abqaiq", "Al-Baḥah",
  "Al-Dammām",
  "Al-Hufūf",
  "Al-Jawf",
  "Al-Kharj (oasis)",
  "Al-Khubar",
  "Al-Qaṭīf",
  "Al-Ṭaʾif",
  "ʿArʿar",
  "Buraydah",
  "Dhahran",
  "Ḥāʾil",
  "Jiddah",
  "Jīzān",
  "Khamīs Mushayt",
  "King Khalīd Military City",
  "Mecca",
  "Medina",
  "Najrān",
  "Ras Tanura",
  "Riyadh",
  "Sakākā",
  "Tabūk",
  "Yanbuʿ",
];

export const Tempcategories = [
  {
    value: "Air Conditioning",
    label: "Air Conditioning",
  },
  {
    value: "Plumbing",
    label: "Plumbing",
  },
  {
    value: "Firefighting",
    label: "Firefighting",
  },
  {
    value: "Electrical",
    label: "Electrical",
  },
  {
    value: "CCTV",
    label: "CCTV",
  },
  {
    value: "Fire alarm",
    label: "Fire alarm",
  },
  {
    value: "Sewer Lines",
    label: "Sewer Lines",
  },
  {
    value: "Glass Doors and Windows",
    label: "Glass Doors and Windows",
  },
  {
    value: "Gyps Work",
    label: "Gyps Work",
  },
  {
    value: "Gypsumboard",
    label: "Gypsumboard",
  },
  {
    label: "Plaster",
    value: "Plaster",
  },
  {
    label: "Block and Breaks",
    value: "Block and Breaks",
  },
  {
    label: "Civil",
    value: "Civil",
  },
  {
    label: "Structure",
    value: "Structure",
  },
  {
    label: "Mechanical",
    value: "Mechanical",
  },
  {
    label: "Electromechanical",
    value: "Electromechanical",
  },
  {
    value: "Complete Building",
    label: "Complete Building",
  },
  {
    label: "Cladding",
    value: "Cladding",
  },
  {
    label: "Metal steel Works",
    value: "Metal steel Works",
  },
  {
    label: "Wood Works",
    value: "Wood Works",
  },
  {
    label: "Kitchen Installation",
    value: "Kitchen Installation",
  },
];